on:
  push:
    paths:
      - "android/**"
      - ".github/workflows/android.yaml"
    branches: [ "main" ]
  pull_request:
    paths:
      - "android/**"
      - ".github/workflows/android.yaml"
    branches: [ "main" ]

name: Android

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle

      - name: Build (debug) with Gradle
        working-directory: android
        run: ./gradlew assembleDebug
